# Generated by Django 2.2.7 on 2019-11-20 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_name', models.CharField(max_length=100)),
                ('Dr_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Dr')),
                ('Sub_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Subjects')),
            ],
        ),
    ]
